CREATE TABLE LECCIONES_APRENDIDAS (
    ID INT IDENTITY(1,1) PRIMARY KEY, -- Identificador autoincremental
    CODIGO_EXP VARCHAR(50) NOT NULL, -- Código de la experiencia
    TEMA NVARCHAR(255) NOT NULL, -- Tema de la experiencia
    LUGAR NVARCHAR(255), -- Lugar donde ocurrió
    FECHA_INGRESO DATE NOT NULL, -- Fecha en que se ingresa el registro
    FECHA_EXPERIENCIA DATE, -- Fecha en que ocurrió la experiencia
    USUARIO NVARCHAR(100), -- Usuario que registra la experiencia
    UNIDAD NVARCHAR(100), -- Unidad donde ocurrió
    FUNCION_PRIMARIA_ID INT NOT NULL, -- Relación con la tabla FUNCION_PRIMARIA
    PAIS_ID INT NOT NULL, -- Relación con la tabla PAIS
    PUESTO_ID INT NOT NULL, -- Relación con la tabla PUESTO
    PRIORIDAD_ID INT NOT NULL, -- Relación con la tabla PRIORIDAD
    QUE_SUCEDIO NVARCHAR(255), -- Descripción de lo que sucedió
    PORQUE_SUCEDIO NVARCHAR(255), -- Razón de lo que ocurrió
    COMO_SOLUCIONARLO NVARCHAR(255), -- Solución para el incidente
    OTROS_ANTECEDENTES NVARCHAR(255), -- Otros antecedentes
    CONSTRAINT FK_LECCIONES_FUNCION_PRIMARIA FOREIGN KEY (FUNCION_PRIMARIA_ID) REFERENCES FUNCION_PRIMARIA(ID),
    CONSTRAINT FK_LECCIONES_PAIS FOREIGN KEY (PAIS_ID) REFERENCES PAIS(ID),
    CONSTRAINT FK_LECCIONES_PUESTO FOREIGN KEY (PUESTO_ID) REFERENCES PUESTO(ID),
    CONSTRAINT FK_LECCIONES_PRIORIDAD FOREIGN KEY (PRIORIDAD_ID) REFERENCES PRIORIDAD(ID)
);

CREATE TABLE ARCHIVO_LECCIONES (
    ID INT IDENTITY(1,1) PRIMARY KEY, -- Identificador autoincremental
    LECCION_ID INT NOT NULL, -- Relación con la tabla LECCIONES_APRENDIDAS
    PDF_BASE64 NVARCHAR(MAX), -- PDF en formato Base64 cargado por el usuario
    JPG_BASE64 NVARCHAR(MAX), -- Imagen JPG en formato Base64 cargada por el usuario
    INFORME_BASE64 NVARCHAR(MAX), -- Informe generado en formato Base64
    CONSTRAINT FK_ARCHIVOS_LECCIONES FOREIGN KEY (LECCION_ID) REFERENCES LECCIONES_APRENDIDAS(ID)
);

CREATE TABLE LOG_VER_ARCHIVO (
    ID INT PRIMARY KEY IDENTITY(1,1), -- Llave primaria con auto-incremento
    EXPERIENCIA_ID INT NOT NULL, -- Obligatorio
    PERSONA INT NULL, -- Puede ser NULL
    FECHA DATETIME NULL, -- Puede ser NULL
    PROPIETARIO INT NOT NULL, -- Obligatorio
    CREACION DATETIME NULL, -- Puede ser NULL
    USUARIO INT NOT NULL, -- Obligatorio
    ACTUALIZACION DATETIME NULL, -- Puede ser NULL
    ESTADO INT NOT NULL, -- Obligatorio
    IP NVARCHAR(MAX) NULL, -- Puede ser NULL
);

CREATE TABLE PRIORIDAD (
    ID INT IDENTITY(1,1) PRIMARY KEY, -- Identificador autoincremental
    NOMBRE NVARCHAR(50) NOT NULL -- Nombre del nivel de prioridad
);

INSERT INTO PRIORIDAD (NOMBRE) VALUES
('NORMAL'),
('URGENTE'),
('MUY URGENTE')

CREATE TABLE FUNCION_PRIMARIA (
    ID INT IDENTITY(1,1) PRIMARY KEY, -- Identificador autoincremental
    NOMBRE NVARCHAR(50) NOT NULL -- Nombre del nivel de prioridad
);

INSERT INTO FUNCION_PRIMARIA (NOMBRE) VALUES
('PERSONAL'),
('INTELIGENCIA'),
('OPERACIONES'),
('LOGISTICA'),
('PLANES Y POLITICAS'),
('MANDO Y CONTROL'),
('DOCTRINA Y ENTRENAMIENTO'),
('FINANZAS'),
('ASUNTOS CIVILES Y ADMINISTRACION TERRITORIAL')

CREATE TABLE PAIS (
    ID INT IDENTITY(1,1) PRIMARY KEY, -- Identificador autoincremental
    NOMBRE NVARCHAR(50) NOT NULL -- Nombre del nivel de prioridad
);

INSERT INTO PAIS (NOMBRE) VALUES ('Afganistán');
INSERT INTO PAIS (NOMBRE) VALUES ('Albania');
INSERT INTO PAIS (NOMBRE) VALUES ('Alemania');
INSERT INTO PAIS (NOMBRE) VALUES ('Andorra');
INSERT INTO PAIS (NOMBRE) VALUES ('Angola');
INSERT INTO PAIS (NOMBRE) VALUES ('Antigua y Barbuda');
INSERT INTO PAIS (NOMBRE) VALUES ('Arabia Saudita');
INSERT INTO PAIS (NOMBRE) VALUES ('Argelia');
INSERT INTO PAIS (NOMBRE) VALUES ('Argentina');
INSERT INTO PAIS (NOMBRE) VALUES ('Armenia');
INSERT INTO PAIS (NOMBRE) VALUES ('Australia');
INSERT INTO PAIS (NOMBRE) VALUES ('Austria');
INSERT INTO PAIS (NOMBRE) VALUES ('Azerbaiyán');
INSERT INTO PAIS (NOMBRE) VALUES ('Bahamas');
INSERT INTO PAIS (NOMBRE) VALUES ('Bahréin');
INSERT INTO PAIS (NOMBRE) VALUES ('Bangladés');
INSERT INTO PAIS (NOMBRE) VALUES ('Barbados');
INSERT INTO PAIS (NOMBRE) VALUES ('Bélgica');
INSERT INTO PAIS (NOMBRE) VALUES ('Belice');
INSERT INTO PAIS (NOMBRE) VALUES ('Benín');
INSERT INTO PAIS (NOMBRE) VALUES ('Bielorrusia');
INSERT INTO PAIS (NOMBRE) VALUES ('Bolivia');
INSERT INTO PAIS (NOMBRE) VALUES ('Bosnia y Herzegovina');
INSERT INTO PAIS (NOMBRE) VALUES ('Botsuana');
INSERT INTO PAIS (NOMBRE) VALUES ('Brasil');
INSERT INTO PAIS (NOMBRE) VALUES ('Brunéi');
INSERT INTO PAIS (NOMBRE) VALUES ('Bulgaria');
INSERT INTO PAIS (NOMBRE) VALUES ('Burkina Faso');
INSERT INTO PAIS (NOMBRE) VALUES ('Burundi');
INSERT INTO PAIS (NOMBRE) VALUES ('Cabo Verde');
INSERT INTO PAIS (NOMBRE) VALUES ('Camerún');
INSERT INTO PAIS (NOMBRE) VALUES ('Canadá');
INSERT INTO PAIS (NOMBRE) VALUES ('Catar');
INSERT INTO PAIS (NOMBRE) VALUES ('Chad');
INSERT INTO PAIS (NOMBRE) VALUES ('Chile');
INSERT INTO PAIS (NOMBRE) VALUES ('China');
INSERT INTO PAIS (NOMBRE) VALUES ('Chipre');
INSERT INTO PAIS (NOMBRE) VALUES ('Colombia');
INSERT INTO PAIS (NOMBRE) VALUES ('Comoras');
INSERT INTO PAIS (NOMBRE) VALUES ('Congo');
INSERT INTO PAIS (NOMBRE) VALUES ('Corea del Norte');
INSERT INTO PAIS (NOMBRE) VALUES ('Corea del Sur');
INSERT INTO PAIS (NOMBRE) VALUES ('Costa de Marfil');
INSERT INTO PAIS (NOMBRE) VALUES ('Costa Rica');
INSERT INTO PAIS (NOMBRE) VALUES ('Croacia');
INSERT INTO PAIS (NOMBRE) VALUES ('Cuba');
INSERT INTO PAIS (NOMBRE) VALUES ('Dinamarca');
INSERT INTO PAIS (NOMBRE) VALUES ('Dominica');
INSERT INTO PAIS (NOMBRE) VALUES ('Ecuador');
INSERT INTO PAIS (NOMBRE) VALUES ('Egipto');
INSERT INTO PAIS (NOMBRE) VALUES ('El Salvador');
INSERT INTO PAIS (NOMBRE) VALUES ('Emiratos Árabes Unidos');
INSERT INTO PAIS (NOMBRE) VALUES ('Eslovenia');
INSERT INTO PAIS (NOMBRE) VALUES ('España');
INSERT INTO PAIS (NOMBRE) VALUES ('Estados Unidos');
INSERT INTO PAIS (NOMBRE) VALUES ('Estonia');
INSERT INTO PAIS (NOMBRE) VALUES ('Etiopía');
INSERT INTO PAIS (NOMBRE) VALUES ('Fiji');
INSERT INTO PAIS (NOMBRE) VALUES ('Filipinas');
INSERT INTO PAIS (NOMBRE) VALUES ('Finlandia');
INSERT INTO PAIS (NOMBRE) VALUES ('Francia');
INSERT INTO PAIS (NOMBRE) VALUES ('Gabón');
INSERT INTO PAIS (NOMBRE) VALUES ('Gambia');
INSERT INTO PAIS (NOMBRE) VALUES ('Georgia');
INSERT INTO PAIS (NOMBRE) VALUES ('Ghana');
INSERT INTO PAIS (NOMBRE) VALUES ('Grecia');
INSERT INTO PAIS (NOMBRE) VALUES ('Granada');
INSERT INTO PAIS (NOMBRE) VALUES ('Guatemala');
INSERT INTO PAIS (NOMBRE) VALUES ('Guinea');
INSERT INTO PAIS (NOMBRE) VALUES ('Guinea Ecuatorial');
INSERT INTO PAIS (NOMBRE) VALUES ('Guinea-Bisáu');
INSERT INTO PAIS (NOMBRE) VALUES ('Haití');
INSERT INTO PAIS (NOMBRE) VALUES ('Honduras');
INSERT INTO PAIS (NOMBRE) VALUES ('Hungría');
INSERT INTO PAIS (NOMBRE) VALUES ('India');
INSERT INTO PAIS (NOMBRE) VALUES ('Indonesia');
INSERT INTO PAIS (NOMBRE) VALUES ('Irán');
INSERT INTO PAIS (NOMBRE) VALUES ('Iraq');
INSERT INTO PAIS (NOMBRE) VALUES ('Irlanda');
INSERT INTO PAIS (NOMBRE) VALUES ('Islacia');
INSERT INTO PAIS (NOMBRE) VALUES ('Islas Marshall');
INSERT INTO PAIS (NOMBRE) VALUES ('Islas Salomón');
INSERT INTO PAIS (NOMBRE) VALUES ('Italia');
INSERT INTO PAIS (NOMBRE) VALUES ('Jamaica');
INSERT INTO PAIS (NOMBRE) VALUES ('Japón');
INSERT INTO PAIS (NOMBRE) VALUES ('Jordania');
INSERT INTO PAIS (NOMBRE) VALUES ('Kazajistán');
INSERT INTO PAIS (NOMBRE) VALUES ('Kenia');
INSERT INTO PAIS (NOMBRE) VALUES ('Kirguistán');
INSERT INTO PAIS (NOMBRE) VALUES ('Kiribati');
INSERT INTO PAIS (NOMBRE) VALUES ('Kuwait');
INSERT INTO PAIS (NOMBRE) VALUES ('Laos');
INSERT INTO PAIS (NOMBRE) VALUES ('Lesoto');
INSERT INTO PAIS (NOMBRE) VALUES ('Letonia');
INSERT INTO PAIS (NOMBRE) VALUES ('Líbano');
INSERT INTO PAIS (NOMBRE) VALUES ('Liberia');
INSERT INTO PAIS (NOMBRE) VALUES ('Libia');
INSERT INTO PAIS (NOMBRE) VALUES ('Liechtenstein');
INSERT INTO PAIS (NOMBRE) VALUES ('Lituania');
INSERT INTO PAIS (NOMBRE) VALUES ('Luxemburgo');
INSERT INTO PAIS (NOMBRE) VALUES ('Malasia');
INSERT INTO PAIS (NOMBRE) VALUES ('Malawi');
INSERT INTO PAIS (NOMBRE) VALUES ('Maldivas');
INSERT INTO PAIS (NOMBRE) VALUES ('Malta');
INSERT INTO PAIS (NOMBRE) VALUES ('Marruecos');
INSERT INTO PAIS (NOMBRE) VALUES ('Mauricio');
INSERT INTO PAIS (NOMBRE) VALUES ('Mauritania');
INSERT INTO PAIS (NOMBRE) VALUES ('México');
INSERT INTO PAIS (NOMBRE) VALUES ('Moldavia');
INSERT INTO PAIS (NOMBRE) VALUES ('Mónaco');
INSERT INTO PAIS (NOMBRE) VALUES ('Mongolia');
INSERT INTO PAIS (NOMBRE) VALUES ('Montenegro');
INSERT INTO PAIS (NOMBRE) VALUES ('Mozambique');
INSERT INTO PAIS (NOMBRE) VALUES ('Namibia');
INSERT INTO PAIS (NOMBRE) VALUES ('Nauru');
INSERT INTO PAIS (NOMBRE) VALUES ('Nepal');
INSERT INTO PAIS (NOMBRE) VALUES ('Nicaragua');
INSERT INTO PAIS (NOMBRE) VALUES ('Nigeria');
INSERT INTO PAIS (NOMBRE) VALUES ('Noruega');
INSERT INTO PAIS (NOMBRE) VALUES ('Nueva Zelanda');
INSERT INTO PAIS (NOMBRE) VALUES ('Omán');
INSERT INTO PAIS (NOMBRE) VALUES ('Países Bajos');
INSERT INTO PAIS (NOMBRE) VALUES ('Pakistán');
INSERT INTO PAIS (NOMBRE) VALUES ('Palaos');
INSERT INTO PAIS (NOMBRE) VALUES ('Panamá');
INSERT INTO PAIS (NOMBRE) VALUES ('Papúa Nueva Guinea');
INSERT INTO PAIS (NOMBRE) VALUES ('Paraguay');
INSERT INTO PAIS (NOMBRE) VALUES ('Perú');
INSERT INTO PAIS (NOMBRE) VALUES ('Polonia');
INSERT INTO PAIS (NOMBRE) VALUES ('Portugal');
INSERT INTO PAIS (NOMBRE) VALUES ('Reino Unido');
INSERT INTO PAIS (NOMBRE) VALUES ('República Centroafricana');
INSERT INTO PAIS (NOMBRE) VALUES ('República Checa');
INSERT INTO PAIS (NOMBRE) VALUES ('República del Congo');
INSERT INTO PAIS (NOMBRE) VALUES ('República Dominicana');
INSERT INTO PAIS (NOMBRE) VALUES ('Rumanía');
INSERT INTO PAIS (NOMBRE) VALUES ('Rusia');
INSERT INTO PAIS (NOMBRE) VALUES ('Rwanda');
INSERT INTO PAIS (NOMBRE) VALUES ('Samoa');
INSERT INTO PAIS (NOMBRE) VALUES ('San Cristóbal y Nieves');
INSERT INTO PAIS (NOMBRE) VALUES ('San Marino');
INSERT INTO PAIS (NOMBRE) VALUES ('San Vicente y las Granadinas');
INSERT INTO PAIS (NOMBRE) VALUES ('Santa Lucía');
INSERT INTO PAIS (NOMBRE) VALUES ('Santo Tomé y Príncipe');
INSERT INTO PAIS (NOMBRE) VALUES ('Senegal');
INSERT INTO PAIS (NOMBRE) VALUES ('Serbia');
INSERT INTO PAIS (NOMBRE) VALUES ('Seychelles');
INSERT INTO PAIS (NOMBRE) VALUES ('Sierra Leona');
INSERT INTO PAIS (NOMBRE) VALUES ('Singapur');
INSERT INTO PAIS (NOMBRE) VALUES ('Eslovaquia');
INSERT INTO PAIS (NOMBRE) VALUES ('Eslovenia');
INSERT INTO PAIS (NOMBRE) VALUES ('Somalia');
INSERT INTO PAIS (NOMBRE) VALUES ('Sudáfrica');
INSERT INTO PAIS (NOMBRE) VALUES ('Sudán');
INSERT INTO PAIS (NOMBRE) VALUES ('Suecia');
INSERT INTO PAIS (NOMBRE) VALUES ('Suiza');
INSERT INTO PAIS (NOMBRE) VALUES ('Siria');
INSERT INTO PAIS (NOMBRE) VALUES ('Tailandia');
INSERT INTO PAIS (NOMBRE) VALUES ('Taiwán');
INSERT INTO PAIS (NOMBRE) VALUES ('Tanzania');
INSERT INTO PAIS (NOMBRE) VALUES ('Tayikistán');
INSERT INTO PAIS (NOMBRE) VALUES ('Togo');
INSERT INTO PAIS (NOMBRE) VALUES ('Tonga');
INSERT INTO PAIS (NOMBRE) VALUES ('Trinidad y Tobago');
INSERT INTO PAIS (NOMBRE) VALUES ('Túnez');
INSERT INTO PAIS (NOMBRE) VALUES ('Turkmenistán');
INSERT INTO PAIS (NOMBRE) VALUES ('Turquía');
INSERT INTO PAIS (NOMBRE) VALUES ('Uganda');
INSERT INTO PAIS (NOMBRE) VALUES ('Ucrania');
INSERT INTO PAIS (NOMBRE) VALUES ('Uruguay');
INSERT INTO PAIS (NOMBRE) VALUES ('Uzbekistán');
INSERT INTO PAIS (NOMBRE) VALUES ('Vanuatu');
INSERT INTO PAIS (NOMBRE) VALUES ('Vaticano');
INSERT INTO PAIS (NOMBRE) VALUES ('Venezuela');
INSERT INTO PAIS (NOMBRE) VALUES ('Vietnam');
INSERT INTO PAIS (NOMBRE) VALUES ('Yemen');
INSERT INTO PAIS (NOMBRE) VALUES ('Zambia');
INSERT INTO PAIS (NOMBRE) VALUES ('Zimbabue');

CREATE TABLE PUESTO (
    ID INT IDENTITY(1,1) PRIMARY KEY, -- Identificador autoincremental
    NOMBRE NVARCHAR(255) NOT NULL -- Nombre del nivel de prioridad
);

INSERT INTO PUESTO (NOMBRE) VALUES ('ABASTECEDOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('ADMINISTR. ALMACÉN MÓVIL');
INSERT INTO PUESTO (NOMBRE) VALUES ('ADMINISTR. LAVANDERÍA Y BAÑOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('AGRUPACIÓN DE COMANDOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('AGRUPACIÓN DE FUERZAS ESPECIALES');
INSERT INTO PUESTO (NOMBRE) VALUES ('AGRUPACIÓN ESPECIAL DE MONTAÑA');
INSERT INTO PUESTO (NOMBRE) VALUES ('ALARIFE Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('ALARIFE Y RADIOPERADOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('ANESTESISTA');
INSERT INTO PUESTO (NOMBRE) VALUES ('APUNT. AMETR. LIVIANA');
INSERT INTO PUESTO (NOMBRE) VALUES ('APUNT. AMETR.LIVIANA Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('APUNT. AMETR.PES. Y PARAMEDICO');
INSERT INTO PUESTO (NOMBRE) VALUES ('APUNT. DE FUS. AMETR. LIVIANA');
INSERT INTO PUESTO (NOMBRE) VALUES ('APUNT. LZA.COHETE RECARGABLE');
INSERT INTO PUESTO (NOMBRE) VALUES ('APUNT. MORTERO LIVIANO');
INSERT INTO PUESTO (NOMBRE) VALUES ('APUNTADOR DE AMETRALLADORA');
INSERT INTO PUESTO (NOMBRE) VALUES ('APUNTADOR FUSIL AMETR. LIV.');
INSERT INTO PUESTO (NOMBRE) VALUES ('APUNTADOR LZC. RECARGABLE');
INSERT INTO PUESTO (NOMBRE) VALUES ('APUNTADOR LZG. MULTIPLE');
INSERT INTO PUESTO (NOMBRE) VALUES ('ARMERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('ARTILLERO DE TORRE');
INSERT INTO PUESTO (NOMBRE) VALUES ('ASESOR APOYO DE FUEGO');
INSERT INTO PUESTO (NOMBRE) VALUES ('ASESOR CONDUCCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('ASESOR FUEGOS ANTIBLINDAJE');
INSERT INTO PUESTO (NOMBRE) VALUES ('ASESOR INGENIEROS Y CBRN');
INSERT INTO PUESTO (NOMBRE) VALUES ('ASESOR JURIDICO');
INSERT INTO PUESTO (NOMBRE) VALUES ('ASESOR MÉDICO');
INSERT INTO PUESTO (NOMBRE) VALUES ('ASESOR S-1');
INSERT INTO PUESTO (NOMBRE) VALUES ('ASESOR S-1, S-4');
INSERT INTO PUESTO (NOMBRE) VALUES ('ASESOR TÉCNICO');
INSERT INTO PUESTO (NOMBRE) VALUES ('ASESOR VETERINARIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('ASISTENTE DE E.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUDITOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. ABAST.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. ABAST. Y COND. CUADRIMOTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. ABASTEC.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. ALMACÉN MÓVIL C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. APOYO ADMINISTRATIVO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. DE EVACUACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. DE INTELIGENCIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. DE LOGÍSTICA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. DE MANT.DE MAT. DE GUERRA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. DE RANCHO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. EQ. ILUMINACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. INSTALACIONES MORTUORIAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. INTELIGENCIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. MANT. Y RADIOPERADOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. MDO. Y CTL.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. OBSERV. ADELANTADO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. OP. EQ. INGENIEROS');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. OPERADOR EQ. INGENIEROS');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. PL. MAYOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. PLANA MAYOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. RECONOC.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. REEMPLAZOS OFICIALES');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. REEMPLAZOS SLTP / SLCs.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. REEMPLAZOS SUBOFICIALES');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUX. TELEC. Y APUNT. FUS. AS. LIV.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILAR MANTENIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR ABAST.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR ABASTECIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR ADM. PERS.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR ADM. PERSONAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR ADM. TERRITORIAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR ADM. Y GESTIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR ADMINISTRATIVO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR AMB. BAT.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR AMBIENTE BATALLA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR APOYO ADM.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR ASUNTOS CIVILES');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR BAÑOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR CALCULISTA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR CEREMONIAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR COMUNICACIONES');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR CONDUCCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR CORRESPONDENCIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DE APOYO ADM.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DE CONTRAINTELIGENCIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DE CORRESPONDENCIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DE ENFERMERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DE HERRADOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DE INTELIGENCIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DE LOGÍSTICA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DE MANDO Y CONTROL');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DE MANTENIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DE OPERACIONES');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DE PERSONAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DE PL. MAYOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DEPOSITO DE CAIDOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DOCTRINA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR DUCHAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR ENFERMERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR ENTRENAMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR EQ. PURIF. DE AGUA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR EVAC. CAIDOS C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR EVAC. CAIDOS Y RADIOP.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR GUERRA ELECTRONICA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR INGENIEROS Y C.V.MEC.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR LAVANDERÍA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR MANDO Y CONTROL');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR MANT. Y AYTE. C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR MANTENIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR O. A.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR OBTENCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR OBTENCIÓN Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR OPS. AÉREAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR OPS. FUTURAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR OPS. Y SOPORTE');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR PLANES');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR PLANIFICACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR POLÍTICAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR PURIFICADOR AGUA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR REEMPL. OFICIALES');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR REEMPL. SLC-SLTP Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR REEMPL. SUBOFICIALES');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR REEMPLAZOS Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR REEMPLAZOS Y 2º C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR SANIDAD');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR SEGURIDAD Y REDES');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR S-1');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR S-2');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR S-3');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR TRANSPORTE Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR TRANSPORTE Y C.V.MEC.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR TRANSPORTE Y 2º C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR VETERINARIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR Y C.V.MEC.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR Y RADIOPERADOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('AUXILIAR Y 2º C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AYUDANTE DE RANCHERO Y RADIOP.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AYUDANTE GASFITER Y 2º C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AYUDANTE PANADERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AYUDANTE RANCHERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('AYUDANTE RANCHERO Y AYTE. C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AYUDANTE RANCHERO Y RADIOP.');
INSERT INTO PUESTO (NOMBRE) VALUES ('AYUDANTE RANCHERO Y 2º C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('BATALLÓN DE HELICÓPTEROS');
INSERT INTO PUESTO (NOMBRE) VALUES ('BATALLÓN DE INFANTERÍA BLINDADO');
INSERT INTO PUESTO (NOMBRE) VALUES ('BATALLÓN DE INFANTERÍA DE MÑA.');
INSERT INTO PUESTO (NOMBRE) VALUES ('BATALLÓN DE INGENIEROS I. DE.');
INSERT INTO PUESTO (NOMBRE) VALUES ('BATALLÓN DE PARACAIDISTAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('BATALLÓN DE TELECOMUNICACIONES');
INSERT INTO PUESTO (NOMBRE) VALUES ('BATALLÓN LOGÍSTICO Y ADM. I DE');
INSERT INTO PUESTO (NOMBRE) VALUES ('BATERÍA LOGÍSTICA');
INSERT INTO PUESTO (NOMBRE) VALUES ('BATERÍA PLANA MAYOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('BOMBERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('BOMBERO Y 2º. C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CAMILLERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CAMILLERO Y AYTE. C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CAMILLERO Y 2º C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CAPELLAN EVANGELICO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CAPELLAN OTROS CREDOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('CARPINTERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDLLA. ADMINISTRACIÓN DE RED');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDLLA. PTO. MANDO ALTERNATIVO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDRLLA. APOYO CONSTR. GENERAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDRLLA. APOYO CONSTR. HORIZ.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDRLLA. APOYO PUENTES MECANO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDRLLA. COMPACTACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDRLLA. CONSTR. GENERAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. BATALLÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. CARRO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. COMPAÑÍA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE  PELOTÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE AGRUPACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE AGRUP.FZAS. ESPECIALES');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE BATALLÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE BATERÍA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE BATERÍA Y S-3');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE CARRO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE CARRO Y AUX. PL. MAYOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE CDRLLA. (TEC.ESPEC.ADM.TI.)');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE COMPAÑÍA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE DE COMPAÑÍA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE CUADRILLA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE CUADRILLA Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE DIVISIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE EQUIPO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCALÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCALÓN (ABAST.)');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCALÓN, AUXILIAR S-2');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCALÓN, S-1 / S-4');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCALÓN, S-1 Y S-4');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCALÓN Y CARRO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCALÓN Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCALÓN Y C.V.MOT.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCALÓN Y S-1');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCALÓN Y S-2');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCALÓN Y S-3');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCALÓN Y S-4');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCUADRA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCUADRA REEMPL.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE ESCUADRA Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE GRUPO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE PATR. Y COND.CUADRIMOT.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE PATRULLA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE PATRULLA Y C.CUADRIMOTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE PATRULLA Y F.T.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE PELOTON');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE PELOTÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE PELOTÓN Y OF. DE BATERIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE PELOTÓN Y OF. DE BATERÍA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE PELOTÓN Y S-2');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE PELOTÓN Y S-3');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE PIEZA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE DE PIEZA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE PIEZA Y APUNTADOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE SECCION');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE SECCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE SUBCUADRILLA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE SUBESCALÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE SUBESCALÓN, S-1 Y S-4');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE SUBESCALÓN Y AUX. S-3');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE SUBESCALÓN Y C.V.A.T.P.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE SUBESCALÓN Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE SUBESCALÓN Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. DE SUBESCLN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. ESCALÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. ESCALÓN / SUBESCLN.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. ESCALÓN Y AUX. S-3');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. PATRULLA Y EQUIPO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. PELOTON / ESCALON');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. SECC. Y OF. DIRECT. DEL FUEGO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. SECCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CDTE. SUBESCALÓN Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CENTRO DE MENSAJES');
INSERT INTO PUESTO (NOMBRE) VALUES ('CEREMONIAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('CIRUJANO');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMANDO');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMANDO DE DIVISIÓN TIPO A');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMP. DE INGENIEROS DE COMBATE');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA ADMINISTRATIVA');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA ARMAS DE APOYO');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA CAZADORES ANDINOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA DE ABASTECIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA DE APOYO DE AVIACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA DE MANTENIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA DE PLANA MAYOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA DE PROTECCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA DE SANIDAD Y VETERIN.');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA DE TELEC. DE COMANDO');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA DE TRANSPORTE');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA FEs');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA FUSILEROS ANDINOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA FUSILEROS BLINDADA');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA HELOS. OPS. GENERALES');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA INFANTERÍA ANDINA');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA INGS. CONSTRUCCIONES');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA LOGÍSTICA');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA MORTEROS BLINDADA');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA PLANA MAYOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMPAÑÍA SERVICIO DE BASE');
INSERT INTO PUESTO (NOMBRE) VALUES ('COMUNICACIONES DEL PERSONAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('COND. VEH. ADM. TRANSP. PERS.');
INSERT INTO PUESTO (NOMBRE) VALUES ('COND. VEH. MEC. Y AUX. ABAST.');
INSERT INTO PUESTO (NOMBRE) VALUES ('COND. VEH. MOT. Y AUX. ABAST.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CONDUCTOR DE MULAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('CONDUCTOR DE RECUA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CONDUCTOR TOLVA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CONDUCTOR VEH. BLINDADO');
INSERT INTO PUESTO (NOMBRE) VALUES ('CONSTRUCTOR DE LÍNEAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('CONTROLADOR AMB. BATALLA');
INSERT INTO PUESTO (NOMBRE) VALUES ('CUADRILLA CONSTRUCCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CUADRILLA ENLACES CONJUNTOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('CUADRILLA INTEGRACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('CUADRILLA PTO. MANDO PRINCIPAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('CUADRILLA RECONOC. Y TOPOGR.');
INSERT INTO PUESTO (NOMBRE) VALUES ('CUARTEL GENERAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('C.V.M');
INSERT INTO PUESTO (NOMBRE) VALUES ('C.V.M. Y AUX. PLANA MAYOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('C.V.M. Y AUX. TELEC.');
INSERT INTO PUESTO (NOMBRE) VALUES ('C.V.M. Y CAMILLERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('C.V.M. Y RADIOPERADOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('C.V.MEC. Y AUX. ABASTTO.');
INSERT INTO PUESTO (NOMBRE) VALUES ('C.V.MOT.');
INSERT INTO PUESTO (NOMBRE) VALUES ('DEPTO. I PERSONAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('DEPTO. II INTELIGENCIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('DEPTO. III OPERACIONES');
INSERT INTO PUESTO (NOMBRE) VALUES ('DEPTO. IV LOGÍSTICA');
INSERT INTO PUESTO (NOMBRE) VALUES ('DEPTO. IX ACAT.');
INSERT INTO PUESTO (NOMBRE) VALUES ('DEPTO. VI MANDO Y CONTROL');
INSERT INTO PUESTO (NOMBRE) VALUES ('DESACTIVADOR E.O.D.');
INSERT INTO PUESTO (NOMBRE) VALUES ('ELECTRICISTA');
INSERT INTO PUESTO (NOMBRE) VALUES ('ENFERMERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('EQUIPO BÁSICO 1');
INSERT INTO PUESTO (NOMBRE) VALUES ('EQUIPO BÁSICO 2');
INSERT INTO PUESTO (NOMBRE) VALUES ('ESCALÓN ABASTECIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('ESCALÓN ALIMENTACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('ESCALÓN APOYO AL PERSONAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('ESCALÓN ATENCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('ESCALÓN BANCO DE SANGRE');
INSERT INTO PUESTO (NOMBRE) VALUES ('ESCALÓN BIENESTAR');
INSERT INTO PUESTO (NOMBRE) VALUES ('ESCALÓN CAMILLEROS');
INSERT INTO PUESTO (NOMBRE) VALUES ('ESCALÓN RECUA REEMPLAZO');
INSERT INTO PUESTO (NOMBRE) VALUES ('EXPLOSIVISTA');
INSERT INTO PUESTO (NOMBRE) VALUES ('EXPLOSIVISTA, C.V.M. Y GUÍA PERRO');
INSERT INTO PUESTO (NOMBRE) VALUES ('EXPLOSIVISTA Y GUÍA PERRO');
INSERT INTO PUESTO (NOMBRE) VALUES ('FRANCO TIRADOR Y COND. MOTOC.');
INSERT INTO PUESTO (NOMBRE) VALUES ('FRANCO TIRADOR Y COND. MOTOC.');
INSERT INTO PUESTO (NOMBRE) VALUES ('FRANCOTIRADOR LIGERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('FRANCOTIRADOR PESADO');
INSERT INTO PUESTO (NOMBRE) VALUES ('FRANCOTIRADOR Y O.A.');
INSERT INTO PUESTO (NOMBRE) VALUES ('FRANCOTIRADOR Y OPERADOR UAV');
INSERT INTO PUESTO (NOMBRE) VALUES ('FUSILERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('FUSILERO Y AUX. PARAMED.');
INSERT INTO PUESTO (NOMBRE) VALUES ('FUSILERO Y AYTE. C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('FUSILERO Y GRANADERO DE FUSIL');
INSERT INTO PUESTO (NOMBRE) VALUES ('FUSILERO Y TIRADOR ESCOGIDO');
INSERT INTO PUESTO (NOMBRE) VALUES ('GASFITER');
INSERT INTO PUESTO (NOMBRE) VALUES ('GIONOMETRISTA');
INSERT INTO PUESTO (NOMBRE) VALUES ('GRUPO DE ARTILLERÍA ATP M-109');
INSERT INTO PUESTO (NOMBRE) VALUES ('HELICOPTERO LIVIANO');
INSERT INTO PUESTO (NOMBRE) VALUES ('HELICOPTERO MEDIANO');
INSERT INTO PUESTO (NOMBRE) VALUES ('ING. COMBATE Y AP.FUSIL AMETR.LIV.');
INSERT INTO PUESTO (NOMBRE) VALUES ('INGENIERO DE COMBATE');
INSERT INTO PUESTO (NOMBRE) VALUES ('INGENIERO DE CONSTRUCCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('JALONERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE CENTRAL DE TIRO');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE CENTRO DE MENSAJES');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE DE DEPARTAMENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE DE DEPTO.');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE DE EQUIPO');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE DE ESTADO MAYOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE DE PLANA MAYOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE DE PLANA MAYOR Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE DE PLANA MAYOR 2º CDTE. BTN.');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE DE SECCION');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE DE SECCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE DE TURNO');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE LÍNEA');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE OPERADORES CENTRAL DE TIRO');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE PL. MAY. Y APT. LZGR. AFUSTE');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE PL. MY. DEL CDTE. BTN.');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEFE PLANA MAYOR Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('JEM.');
INSERT INTO PUESTO (NOMBRE) VALUES ('KINESIOLOGO');
INSERT INTO PUESTO (NOMBRE) VALUES ('LABORATORISTA');
INSERT INTO PUESTO (NOMBRE) VALUES ('LANZADOR MISIL A/A.');
INSERT INTO PUESTO (NOMBRE) VALUES ('LANZADOR MISIL A/BL.');
INSERT INTO PUESTO (NOMBRE) VALUES ('MEC. EQ. TELEC.');
INSERT INTO PUESTO (NOMBRE) VALUES ('MEC. VEH. MOT.');
INSERT INTO PUESTO (NOMBRE) VALUES ('MEC. VEH. MOT.');
INSERT INTO PUESTO (NOMBRE) VALUES ('MECÁNICO');
INSERT INTO PUESTO (NOMBRE) VALUES ('MECÁNICO DE EQ. DE INGENIEROS');
INSERT INTO PUESTO (NOMBRE) VALUES ('MECÁNICO ELECTRICISTA');
INSERT INTO PUESTO (NOMBRE) VALUES ('MECÁNICO ELECTRICO');
INSERT INTO PUESTO (NOMBRE) VALUES ('MECÁNICO HIDRÁULICO');
INSERT INTO PUESTO (NOMBRE) VALUES ('MECÁNICO INSTRUMENTISTA');
INSERT INTO PUESTO (NOMBRE) VALUES ('MECÁNICO VEH. BLINDADO');
INSERT INTO PUESTO (NOMBRE) VALUES ('MECÁNICO VEH. MOTORIZADOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('MECÁNICO Y C.V.BLINDADO');
INSERT INTO PUESTO (NOMBRE) VALUES ('MENSAJERO Y COND. MOTOCIC.');
INSERT INTO PUESTO (NOMBRE) VALUES ('METEOROLOGO');
INSERT INTO PUESTO (NOMBRE) VALUES ('MUNICIONERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('OBSERVADOR ADELANTADO');
INSERT INTO PUESTO (NOMBRE) VALUES ('OFICIAL DE ENLACE');
INSERT INTO PUESTO (NOMBRE) VALUES ('OFICIAL DE ORDENES Y AYDTE. PERS.');
INSERT INTO PUESTO (NOMBRE) VALUES ('OP. CENTRAL TELEFONICA');
INSERT INTO PUESTO (NOMBRE) VALUES ('OP. EQ. DE INGENIEROS');
INSERT INTO PUESTO (NOMBRE) VALUES ('OPERADOR CENTRAL DE TIRO');
INSERT INTO PUESTO (NOMBRE) VALUES ('OPERADOR DE EQ. TELEC.');
INSERT INTO PUESTO (NOMBRE) VALUES ('OPERADOR DE EQUIPO DE TELECOM.');
INSERT INTO PUESTO (NOMBRE) VALUES ('OPERADOR DE MONTACARGA');
INSERT INTO PUESTO (NOMBRE) VALUES ('OPERADOR ENVASADOR AGUA');
INSERT INTO PUESTO (NOMBRE) VALUES ('PANADERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PARAMÉDICO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PATRULLA DE ENLACE');
INSERT INTO PUESTO (NOMBRE) VALUES ('PATRULLA DE REC. Y TOPOGRAF.');
INSERT INTO PUESTO (NOMBRE) VALUES ('PATRULLA FEs ALFA');
INSERT INTO PUESTO (NOMBRE) VALUES ('PATRULLA FEs BRAVO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PATRULLA FEs. CHARLY');
INSERT INTO PUESTO (NOMBRE) VALUES ('PATRULLA FEs. DELTA');
INSERT INTO PUESTO (NOMBRE) VALUES ('PATRULLA FEs ECO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PATRULLA FEs FOXTROX');
INSERT INTO PUESTO (NOMBRE) VALUES ('PATRULLA RECCTO. Y GUÍAS LANZ.');
INSERT INTO PUESTO (NOMBRE) VALUES ('PATRULLA RECONOCOCIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PATRULLERO C.MOTOC.');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN ABASTECIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN ADMINISTRATIVO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN ANTIBLINDAJE MISILES');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN ATENCIÓN SANITARIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN CUARTEL GENERAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN DE AVIONES');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN DE HELICOPTEROS');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN DE MORTEROS');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN DE SANIDAD Y VETERINARIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN ESTABILIZACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN HELOS. DE ASALTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN HELOS. LIGERO DE ATAQUE');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN HELOS. LIVIANOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN HELOS. MEDIANOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN MANTENIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN MANTTO. SISTEMAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN MANTTO. VEHÍCULOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN MORTEROS A LOMO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN PIEZAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN PLANA MAYOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN PROTECCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN PUESTO DE MANDO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN RECEP. Y EVACUACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN SALUD PÚBL. Y VETER.');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTON TRANSP. MIXTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN TRANSPORTE');
INSERT INTO PUESTO (NOMBRE) VALUES ('PELOTÓN TRANSPORTE PESADO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PIEZA ART. 105 mm. TRACTADA');
INSERT INTO PUESTO (NOMBRE) VALUES ('PIEZA ARTILLERIA M-109');
INSERT INTO PUESTO (NOMBRE) VALUES ('PIEZA MORTERO MEDIANA');
INSERT INTO PUESTO (NOMBRE) VALUES ('PILOTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('PLANA MAYOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('POLICIA MILITAR');
INSERT INTO PUESTO (NOMBRE) VALUES ('PSICÓLOGO');
INSERT INTO PUESTO (NOMBRE) VALUES ('RADIOPERADOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('RADIOPERADOR ARMADA');
INSERT INTO PUESTO (NOMBRE) VALUES ('RADIOPERADOR FACH');
INSERT INTO PUESTO (NOMBRE) VALUES ('RADIOPERADOR, F.T. Y C.V.MOT.');
INSERT INTO PUESTO (NOMBRE) VALUES ('RADIOPERADOR, MENSAJERO Y C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('RADIOPERADOR Y APUNT. LZCD.');
INSERT INTO PUESTO (NOMBRE) VALUES ('RADIOPERADOR Y AUX. PL. MAYOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('RADIOPERADOR Y AYTE. C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('RADIOPERADOR Y AY7TE. C.V.M.');
INSERT INTO PUESTO (NOMBRE) VALUES ('RADIOPERADOR Y COND. MULAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('RANCHERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('RECCTO. Y COND. MOTOCICLETA');
INSERT INTO PUESTO (NOMBRE) VALUES ('RECONOCIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('REGISTRADOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('RESCATISTA');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN ADM. DE PERSONAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN ADM. TERRITORIAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN ADQUISICIÓN DE OBJETIVOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN AMETR. MEDIANAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN APOYO ADMINISTRATIVO');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN BIENESTAR');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN COMUNIC. DEL PERSONAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN CONDUCCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN CONSTR. GENERAL');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN DE RECONOCIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN DIRECCIÓN DEL FUEGO');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN INTELIGENCIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN LOGÍSTICA');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN MANTENIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN MISILES');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN OPERAC. Y SOPORTE');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCION PERTRECHOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN PLANES/POLÍTICAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN PROTECCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN PROTECCIÓN INSTALACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN RECONOCIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN SANIDAD');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN SEGURIDAD Y REDES');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN SUBSISTENCIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN S-1 / S-4');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN S-2 / S-3');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN S-6');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN TELECOMUNICACIONES');
INSERT INTO PUESTO (NOMBRE) VALUES ('SECCIÓN TRANSPORTE');
INSERT INTO PUESTO (NOMBRE) VALUES ('SEGUNDO CDTE. AGRUP. FZAS. ESP.');
INSERT INTO PUESTO (NOMBRE) VALUES ('SIRV. MUNICIONERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('SIRVIENTE');
INSERT INTO PUESTO (NOMBRE) VALUES ('SOM DE BATALLÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBCDLLA. INTEGR. MICROONDAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN ABASTECIMIENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN AGUA');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN ALIMENTACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN BANCO DE SANGRE');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN COCINAS');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN COMBUSTIBLE');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN DISTRIBUCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALON MANT. ARMAMENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN MANT. ARMAMENTO');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN MANT. TERRESTRE');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN ODONTOLOGÍA');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN PANADERÍA');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN PERTRECHOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN PROTECCIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN RECUPERACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN REGISTRO CAÍDOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN SANIDAD');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN SERV. GENERALES');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN SISTEMAS MECÁNICOS');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN SUBSISTENCIA');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUBESCALÓN TRANSPORTE');
INSERT INTO PUESTO (NOMBRE) VALUES ('SUPERV. MANTTO. E INSTR. AV. TIRO');
INSERT INTO PUESTO (NOMBRE) VALUES ('TALABARTERO');
INSERT INTO PUESTO (NOMBRE) VALUES ('TECNOLOGO MÉDICO');
INSERT INTO PUESTO (NOMBRE) VALUES ('TENDEDOR DE LINEA Y TELEFONISTA');
INSERT INTO PUESTO (NOMBRE) VALUES ('TIRADOR EMBOSCADO');
INSERT INTO PUESTO (NOMBRE) VALUES ('TOPOGRAFO');
INSERT INTO PUESTO (NOMBRE) VALUES ('TRAUMATOLOGO');
INSERT INTO PUESTO (NOMBRE) VALUES ('2º CDTE. AGRUPACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('2º CDTE. DE AGRUPACIÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('2º CDTE. DE BATALLÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('2º CDTE. DE COMPAÑÍA');
INSERT INTO PUESTO (NOMBRE) VALUES ('2º CDTE. DE PATRULLA');
INSERT INTO PUESTO (NOMBRE) VALUES ('2º CDTE. DE PELOTÓN');
INSERT INTO PUESTO (NOMBRE) VALUES ('2º COMANDANTE');
INSERT INTO PUESTO (NOMBRE) VALUES ('2º CONDUCTOR');
INSERT INTO PUESTO (NOMBRE) VALUES ('2º C.V.MOT.');
INSERT INTO PUESTO (NOMBRE) VALUES ('2DO. CDTE. DE PELOTÓN');



